### ISSUE TITLE
db issue

### ISSUE THREAD

**Issue by sezerakr** [fdciabdul/mangareader.to-Scraper#2]
`const db = require("./db");`
parts give an error that module not found. When install db module on npm and make require("db") it's work until another error called  `await db.insertManga(
               ^
TypeError: db.insertManga is not a function`

**Comment by fdciabdul** [comment]
> `const db = require("./db");` parts give an error that module not found. When install db module on npm and make require("db") it's work until another error called `await db.insertManga( ^ TypeError: db.insertManga is not a function`

oof i forgot about that  , thanks for report

**Comment by fdciabdul** [comment]
> `const db = require("./db");` parts give an error that module not found. When install db module on npm and make require("db") it's work until another error called `await db.insertManga( ^ TypeError: db.insertManga is not a function`

clone again
