### ISSUE TITLE
missing ')' in line 171

### ISSUE THREAD

**Issue by sezerakr** [fdciabdul/mangareader.to-Scraper#3]
Hi, ')' is missing on index.js (line 171)

); => ));

**Comment by sezerakr** [comment]
Download Image |░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░| 0% || 0/100 Chunks || Speed: {speed}Collecting Image from Chapter chapter-2

stuck in here, don't download

**Comment by fdciabdul** [comment]
that's works fine tho 

![image](https://user-images.githubusercontent.com/31664438/141697465-73b29eac-a6e1-41a7-b5ba-3327f9cec421.png)

probably your internet provider blocked the site , try using vpn

**Comment by sezerakr** [comment]
Oh ok, thanks i will try.
